<<<<<<< HEAD:src/app/layout.jsx

=======
>>>>>>> 8206d2d4f37e37a90741b890fee4ba0970a40f1e:src/app/layout.js

import HomePage from './HomePage'

import "./globals.css";

import { Poppins } from "next/font/google";

import { Nunito } from "next/font/google";

import { Analytics } from "@vercel/analytics/react"



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <HomePage />
        
        {children}
        </body>
    </html>
  );
}
